spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vedios
    username: root
    password: Mima1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.em.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - com.em.utils.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8