# 配置数据源相关，使用Alibaba的durid数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vedios
    data-username: root
    password: Mima1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.em.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - com.em.utils.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


